# Generated by Django 3.1.1 on 2021-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('bg_class', models.CharField(max_length=50)),
                ('card_header', models.CharField(max_length=50)),
                ('card_body', models.TextField()),
                ('post_title', models.CharField(max_length=50)),
                ('post_content', models.TextField()),
                ('online_demo', models.URLField(max_length=50)),
                ('overview', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
