# Generated by Django 3.1.1 on 2021-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column='Subject', max_length=50)),
                ('phone_number', models.CharField(blank=True, db_column='Phone Number', max_length=15, null=True)),
                ('email', models.EmailField(db_column='Email Address', max_length=50)),
                ('content', models.TextField(db_column='Content', null=True)),
                ('owner', models.CharField(max_length=50)),
                ('checked', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_column='Read', max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
