# Generated by Django 3.1.1 on 2021-01-09 17:03

import App.account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, db_column='Company name', max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('email_confirmed', models.BooleanField(db_column='Email confirmation', default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('activation_code', models.CharField(default=App.account.models.random_string, max_length=32)),
                ('password_reset_code', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
